name = "ContextVariables"
uuid = "fc3f81ed-7e0a-4cf9-af20-99dcbdf2a20a"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
